spring:
  application:
    name: catalogue-fusees
  datasource:
    url: jdbc:h2:file:./data/fusees
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false
server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
app:
  demo: true
